version: "3"
services:
  mongo_db:
    container_name: mydatabase
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 5200:5200
    env_file:
      - .env
volumes:
  mongo_db: {}